server:
  port: 8081
spring:
  application:
    name: npc-service
  redis:
    url: redis://localhost:6379
    host: localhost
    port: 6379
    client-name: npc-app
opentracing:
  jaeger:
    enabled: true
    http-sender:
      url: http://${JAEGER_HOST}:14268/api/traces
